version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./apps/nginx-reverse-proxy/nginx.conf:/etc/nginx/nginx.conf

  auth:
    build :
      dockerfile: ./apps/auth/Dockerfile
      context : .
    ports:
      - "4000:4000"
    environment:
      - CLIENT_URL=http://localhost:4000/
      - MONGO_URL=mongodb+srv://winterprojectiiitm:ZWSAl0qypIwazq8n@communet.mhdgh6b.mongodb.net/?retryWrites=true&w=majority
      - GOOGLE_CLIENT_ID=248175880781-oehmv64rmqcnga6fqfpuads82g07b98i.apps.googleusercontent.com 
      - GOOGLE_CLIENT_SECRET=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
      - SESSION_SECRET=secret
  
  mail-service:
    build : 
      context :  .
      dockerfile: ./apps/mail-service/Dockerfile
    ports :
      - "3000:3000"
    environment:
      - name=value
      - CLIENT_URL=http://localhost:4000/
      - MONGO_URL=mongodb+srv://winterprojectiiitm:ZWSAl0qypIwazq8n@communet.mhdgh6b.mongodb.net/?retryWrites=true&w=majority
      - GOOGLE_CLIENT_ID=248175880781-oehmv64rmqcnga6fqfpuads82g07b98i.apps.googleusercontent.com 
      - GOOGLE_CLIENT_SECRET=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
      - SESSION_SECRET=secret
      - EMAIL_PORT=3000

    